name: Xshards
version: 1.2.3
main: com.xshards.Xshards
api-version: 1.17

commands:
  shards:
    description: Check your shard balance
    usage: /<command>
  store:
    description: Access the shard shop
    usage: /<command> [edit <slot> <price>]
  afk:
    description: Set yourself as AFK
    usage: /<command>
  setafk:
    description: Set your AFK location
    usage: /<command>
  quitafk:
    description: Quit AFK mode
    usage: /<command>
  afkremove:
    description: Remove your AFK location
    usage: /<command>
  xshards:
    description: Plugin management commands
    usage: /<command> [reload|help]
  transfer:
    description: Transfer shards to other players
    usage: /<command> <player> <amount>
  leaderboard:
    description: View the shards leaderboard
    usage: /<command> [page]

permissions:
  xshards.use:
    description: Allows access to shard and AFK commands
    default: true
  xshards.admin:
    description: Allows access to admin commands
    default: op
  xshards.transfer:
    description: Allows transferring shards to other players
    default: true
  xshards.leaderboard:
    description: Allows viewing the leaderboard
    default: true

softdepend:
  - PlaceholderAPI